# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: PyCellID

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -r
      - name: "Upload coverage to Codecov"
        env:
          CODECOV_TOKEN: '5bcd1416-8c81-4960-aa34-63f2557fc3a6'
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true